import type { LanguageGrammar } from "./types";

const C_KEYWORDS = [
  "auto",
  "break",
  "case",
  "char",
  "const",
  "continue",
  "default",
  "do",
  "double",
  "else",
  "enum",
  "extern",
  "float",
  "for",
  "goto",
  "if",
  "inline",
  "int",
  "long",
  "register",
  "restrict",
  "return",
  "short",
  "signed",
  "sizeof",
  "static",
  "struct",
  "switch",
  "typedef",
  "union",
  "unsigned",
  "void",
  "volatile",
  "while",
] as const;

export const cGrammar: LanguageGrammar = {
  names: ["c", "h"],
  keywords: C_KEYWORDS,
  commentPrefixes: ["//"],
  stringDelimiters: ["'", '"'],
  identifierStart: /[A-Za-z_]/,
  identifierPart: /[A-Za-z0-9_]/,
  numberLiteral: /^(?:0[xX][\dA-Fa-f']+|\d[\d']*(?:\.\d[\d']*)?(?:[eE][+-]?\d+)?[fFlLuU]*)$/,
  punctuation: ["{", "}", "(", ")", "[", "]", ",", ".", ";", ":"],
  operatorChars: /[=+\-*/%!?<>&|^~]/,
  declarationKeywords: ["typedef"],
  typeKeywords: ["struct", "union", "enum", "typedef"],
};
