import type { LanguageGrammar } from "./types";

const CPP_KEYWORDS = [
  "alignas",
  "alignof",
  "auto",
  "bool",
  "break",
  "case",
  "catch",
  "char",
  "class",
  "const",
  "consteval",
  "constexpr",
  "constinit",
  "continue",
  "decltype",
  "default",
  "delete",
  "do",
  "double",
  "else",
  "enum",
  "explicit",
  "export",
  "extern",
  "false",
  "float",
  "for",
  "friend",
  "if",
  "inline",
  "int",
  "long",
  "mutable",
  "namespace",
  "new",
  "noexcept",
  "nullptr",
  "operator",
  "private",
  "protected",
  "public",
  "register",
  "requires",
  "return",
  "short",
  "signed",
  "sizeof",
  "static",
  "struct",
  "switch",
  "template",
  "this",
  "throw",
  "true",
  "try",
  "typedef",
  "typename",
  "union",
  "unsigned",
  "using",
  "virtual",
  "void",
  "volatile",
  "while",
] as const;

export const cppGrammar: LanguageGrammar = {
  names: ["cpp", "c++", "cc", "cxx", "hpp", "hh", "hxx"],
  keywords: CPP_KEYWORDS,
  commentPrefixes: ["//"],
  stringDelimiters: ["'", '"'],
  identifierStart: /[A-Za-z_]/,
  identifierPart: /[A-Za-z0-9_]/,
  numberLiteral: /^(?:0[xX][\dA-Fa-f']+|\d[\d']*(?:\.\d[\d']*)?(?:[eE][+-]?\d+)?[fFlLuU]*)$/,
  punctuation: ["{", "}", "(", ")", "[", "]", ",", ".", ";", ":", "<", ">"],
  operatorChars: /[=+\-*/%!?<>&|^~]/,
  declarationKeywords: ["class", "struct", "enum", "typedef", "using"],
  typeKeywords: ["class", "struct", "enum", "typename", "using"],
};
