import type { LanguageGrammar } from "./types";

const JAVASCRIPT_KEYWORDS = [
  "as",
  "async",
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "from",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
] as const;

export const javascriptGrammar: LanguageGrammar = {
  names: ["javascript", "js", "jsx"],
  keywords: JAVASCRIPT_KEYWORDS,
  commentPrefixes: ["//"],
  stringDelimiters: ["'", '"', "`"],
  identifierStart: /[A-Za-z_$]/,
  identifierPart: /[A-Za-z0-9_$]/,
  numberLiteral: /^(?:0[xX][\dA-Fa-f_]+|0[bB][01_]+|0[oO][0-7_]+|\d[\d_]*(?:\.\d[\d_]*)?(?:[eE][+-]?\d+)?)$/,
  punctuation: ["{", "}", "(", ")", "[", "]", ",", ".", ";", ":"],
  operatorChars: /[=+\-*/%!?<>&|^~]/,
  declarationKeywords: ["function", "const", "let", "var"],
  typeKeywords: ["class", "extends"],
};
