import type { LanguageGrammar } from "./types";

const PYTHON_KEYWORDS = [
  "and",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "case",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "False",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "match",
  "None",
  "nonlocal",
  "not",
  "or",
  "pass",
  "raise",
  "return",
  "True",
  "try",
  "while",
  "with",
  "yield",
] as const;

export const pythonGrammar: LanguageGrammar = {
  names: ["python", "py"],
  keywords: PYTHON_KEYWORDS,
  commentPrefixes: ["#"],
  stringDelimiters: ["'", '"'],
  identifierStart: /[A-Za-z_]/,
  identifierPart: /[A-Za-z0-9_]/,
  numberLiteral: /^(?:\d[\d_]*(?:\.\d[\d_]*)?(?:[eE][+-]?\d+)?|0[xX][\dA-Fa-f_]+|0[bB][01_]+|0[oO][0-7_]+)$/,
  punctuation: ["{", "}", "(", ")", "[", "]", ",", ".", ";", ":"],
  operatorChars: /[=+\-*/%!?<>&|^~]/,
};
