import type { LanguageGrammar } from "./types";

const RUST_KEYWORDS = [
  "as",
  "async",
  "await",
  "break",
  "const",
  "continue",
  "crate",
  "dyn",
  "else",
  "enum",
  "extern",
  "false",
  "fn",
  "for",
  "if",
  "impl",
  "in",
  "let",
  "loop",
  "match",
  "mod",
  "move",
  "mut",
  "pub",
  "ref",
  "return",
  "self",
  "Self",
  "static",
  "struct",
  "super",
  "trait",
  "true",
  "type",
  "unsafe",
  "use",
  "where",
  "while",
] as const;

export const rustGrammar: LanguageGrammar = {
  names: ["rust", "rs"],
  keywords: RUST_KEYWORDS,
  commentPrefixes: ["//"],
  stringDelimiters: ["'", '"'],
  identifierStart: /[A-Za-z_]/,
  identifierPart: /[A-Za-z0-9_]/,
  numberLiteral: /^(?:0[xX][\dA-Fa-f_]+|0[bB][01_]+|0[oO][0-7_]+|\d[\d_]*(?:\.\d[\d_]*)?(?:[eE][+-]?\d+)?(?:u8|u16|u32|u64|u128|usize|i8|i16|i32|i64|i128|isize|f32|f64)?)$/,
  punctuation: ["{", "}", "(", ")", "[", "]", ",", ".", ";", ":", "<", ">"],
  operatorChars: /[=+\-*/%!?<>&|^~]/,
  declarationKeywords: ["fn", "let", "const", "type"],
  typeKeywords: ["struct", "enum", "trait", "impl", "type"],
};
